project_id = "jtaekxrkubhwtqgodvtx"

[functions.search-facebook-interests]
verify_jwt = true

[functions.facebook-post-extractor]
verify_jwt = false

[functions.search-facebook-locations]
verify_jwt = true

[functions.sync-ads-cron]
verify_jwt = true

[functions.process-scheduled-reports]
verify_jwt = true

[functions.setup-cron-rpc]
verify_jwt = true

[functions.nocodb-proxy]
verify_jwt = false